### ISSUE TITLE
Add a meta package that re-exports all we need to use kittik

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/kittik#149]
There is must be a package named `kittik` that will hold modules from other packages and provide CLI feature set:

- [x] Export DeckBuilder
- [x] Export SlideBuilder
- [x] Export AnimationBuilder, AnimationType, AnimationObject, AnimationOptions
- [x] Export ShapeBuilder, ShapeType, ShapeObject, ShapeOptions
- [ ] ~CLI command to run presentation from *.ts file~ there are some issues with that one, for beta will be enough to run ts-node itself

**Comment by ghaiklor** [comment]
Done in 54fdf7e2689de01998fdfce50ad3f5d90e4936df
